GLOSSARY = {
    # === TRADING & STRATEGY TERMS ===
    "Algorithmic Trading": "Automated execution of trades based on predefined rules.",
    "Alpha": "Excess returns generated by a strategy over a benchmark, representing a measure of skill or edge.",
    "Alpha Decay": "The phenomenon where a profitable trading strategy loses its edge over time due to market adaptation.",
    "Backtesting": "The process of evaluating a trading strategy using historical market data to assess its potential performance.",
    "Backtesting Bias": "When a strategy looks great on historical data but fails live. Common causes: overfitting (too many parameters), look-ahead bias (using future info), survivorship bias (only testing survivors).",
    "Backtrader": "A popular open-source Python framework used for backtesting trading strategies.",
    "Bag Holder": "A trader who is stuck with a losing position, often due to poor timing or market conditions.",
    "Beta": "A measure of an asset's sensitivity to market movements, indicating systematic risk.",
    "Bid/Ask": "The prices at which buyers (bid) and sellers (ask) are willing to trade a financial instrument.",
    "Cointegration": "A statistical property describing a long-term equilibrium relationship between two or more non-stationary time series.",
    "Drawdown": "The peak-to-trough decline in a portfolio's value over a specific period, measuring downside risk.",
    "IBKR (Interactive Brokers)": "A global brokerage firm known for its API and support for algorithmic trading.",
    "Meta-Labeling": "A technique where one model's output is used to validate or refine the signals generated by another model.",
    "Overfitting": "A modeling error where a strategy fits historical noise rather than the underlying signal, leading to poor out-of-sample performance.",
    "RSI (Relative Strength Index)": "A momentum oscillator that identifies overbought or oversold conditions in a market.",
    "Statistical Arbitrage": "A trading strategy that exploits temporary mispricings between correlated assets.",
    "Walk-Forward Analysis": "A method for testing a strategy by applying it to rolling windows of future data to simulate real-time trading.",

    # === OPTIONS & DERIVATIVES ===
    "Call/Put Option": "Financial derivatives that give the holder the right, but not the obligation, to buy (call) or sell (put) an underlying asset at a specified price.",
    "Delta": "The rate of change of an option's price relative to changes in the price of the underlying asset.",

    # === RISK MANAGEMENT & METRICS ===
    "CVaR (Conditional Value at Risk)": "Estimates the average loss in the worst 5% of outcomes. More informative than VaR alone because it tells you HOW BAD things get when they go wrong, not just the threshold.",
    "Max Drawdown": "Largest peak-to-trough decline in portfolio value. If your portfolio went from $1,000 to $600, that's a 40% drawdown. Critical for understanding worst-case scenarios.",
    "Sharpe Ratio": "Measures risk-adjusted return by dividing excess return by volatility. A Sharpe > 1.0 is good, > 2.0 is excellent. Think of it as 'bang for your buck' after accounting for risk.",
    "VaR (Value at Risk)": "A statistical measure that estimates the maximum potential loss in value of a portfolio over a defined period for a given confidence interval.",

    # === QUANTITATIVE & STATISTICAL METHODS ===
    "Bayesian Quantile Regression (BQR)": "Forecasts distributional outcomes using probabilistic modeling. Unlike traditional regression that predicts only the average, BQR models the entire distribution including worst-case (Q0.05), median (Q0.5), and best-case (Q0.95) scenarios.",
    "CBQRA (Crypto Bayesian Quantile Regression Analysis)": "The full statistical pipeline: load data → fit Bayesian quantile models → generate forecasts → calculate correlations → create visualizations. 'Running CBQRA' means executing all these steps.",
    "Convergence (MCMC)": "When the MCMC chain stabilizes and is sampling from the correct target distribution. Like stirring a pot until ingredients are evenly mixed. Check trace plots - they should look like 'fuzzy caterpillars' with no trends.",
    "Correlation Matrix": "Grid showing how asset prices move together, ranging from -1 (perfect opposite) to +1 (perfect together). Critical for portfolio diversification - you want LOW correlations between assets to spread risk.",
    "Eigenvalue": "Mathematical concept underlying correlation matrices. If smallest eigenvalue < 0, the matrix isn't positive definite and needs correction. The app handles this automatically - you'll see warnings if it happens.",
    "Fat Tails": "When extreme events happen more often than normal distribution predicts. Crypto has VERY fat tails - 10% daily moves that 'should' happen once per century occur monthly. Monte Carlo uses T-distribution to handle this.",
    "Forecast Distribution": "The full range of possible future outcomes, not just a single point estimate. Shows you the uncertainty inherent in predictions - the 'cone of possibilities' rather than a single line.",
    "MCMC (Markov Chain Monte Carlo)": "Statistical algorithm that draws samples from complex probability distributions. Used in Bayesian analysis to estimate parameters when exact calculation is impossible. 'Sampling' = taking random draws; 'Chain' = sequence where each draw depends on the previous one.",
    "Monte Carlo Simulation": "Runs thousands of 'what-if' scenarios using random price paths constrained by historical volatility and correlations. Like running 1,000 parallel universes to see all possible outcomes.",
    "Positive Definite Matrix": "Technical requirement for correlation/covariance matrices to be mathematically valid. Ensures you can simulate correlated assets without getting impossible results (like negative volatility). The software checks and fixes this automatically.",
    "Posterior Slope (Beta)": "The trend strength parameter estimated from data. In the BQR charts, different slopes across quantiles (Q0.05, Q0.5, Q0.95) reveal regime sensitivity. A flat slope near zero indicates stability; steep or diverging slopes indicate trend sensitivity or regime shifts.",
    "Quantile": "A cut point dividing a probability distribution into intervals. Q0.05 = 5th percentile (95% of outcomes are ABOVE this), Q0.5 = median (50/50 split), Q0.95 = 95th percentile (only 5% of outcomes exceed this).",
    "Regime Sensitivity": "How much an asset's behavior changes with market conditions. High sensitivity = wildly different outcomes in bull vs bear markets. Visible as diverging slopes across BQR quantiles.",
    "Rolling Window": "Analysis period that moves forward through time. '30-day rolling correlation' calculates correlation using the most recent 30 days, updated daily. Shows how relationships evolve.",
    "Student's T-Distribution": "Probability distribution with 'fatter tails' than normal distribution - better captures rare extreme events. Used in Monte Carlo to model realistic crypto crashes and spikes. The 'nu' parameter controls tail thickness.",
    "Trace Diagnostics": "Collection of posterior samples from Bayesian MCMC sampling. Used to verify the model 'converged' (stabilized) and to quantify uncertainty in parameter estimates like slope.",

    # === PORTFOLIO MANAGEMENT ===
    "Allocation Drift": "See 'Portfolio Drift'. When your actual allocations deviate from targets, increasing concentration risk. Monitor regularly and rebalance when drift exceeds threshold (e.g., ±5%).",
    "Annualized Return": "Return scaled to a one-year period for comparison. If you gained 5% in 3 months, annualized ≈ 20% (assuming compounding). Makes short-term and long-term returns comparable.",
    "Beat SP500 Chance": "Percentage of simulations where your portfolio outperforms the S&P 500 benchmark (~8% annual return). Measures whether your strategy justifies the extra risk versus index investing.",
    "Best Case / Worst Case": "Extreme simulation outcomes. Best Case ≈ 95th percentile (only 5% of simulations do better). Worst Case ≈ 5th percentile (only 5% do worse). These are NOT the absolute extremes, just high/low representative scenarios.",
    "Circuit Breaker": "Automatic trading halt or position reduction triggered by extreme moves. Example: 'If 30-day volatility > 2.5x normal, cut positions by 50%' protects against regime changes.",
    "Correlation Breakdown": "When previously correlated assets suddenly move independently (or oppositely). Dangerous because it breaks diversification assumptions - all your 'different' assets might crash together.",
    "Diversification": "Spreading investments across uncorrelated assets to reduce portfolio risk. Effective diversification requires correlations below 0.90 - higher values mean your 'different' assets are essentially the same trade in disguise. This system enforces correlation thresholds as a circuit breaker.",
    "Expected Return": "Average return predicted by the model across all simulations. In risk-return profiles, it's annualized (per year) and expressed as a percentage. Remember: this is the AVERAGE - actual outcomes vary widely!",
    "Flash Crash": "Sudden, severe price drop followed by quick recovery. Example: Asset drops 30%+ in minutes, then recovers within hours. Circuit breakers and stop-losses help protect against these.",
    "Kelly Criterion": "Mathematical formula for optimal position sizing based on edge (expected return) and odds (risk). Full Kelly can be aggressive; most traders use 'fractional Kelly' (e.g., 50% of Kelly) for safety.",
    "Portfolio Drift": "When asset allocations change over time due to different growth rates. If BTC doubles while others stay flat, your 20% BTC allocation becomes 33%+, changing your risk profile. Triggers rebalancing.",
    "Position Sizing": "How much capital to allocate to each asset. NOT just 'equal weight' - should account for volatility, correlation, expected return, and personal risk tolerance. Core of risk management.",
    "Probability Positive": "Percentage of simulations ending with positive returns. If 72%, then 72% of simulated futures are profitable. Useful sanity check - but remember, magnitude matters too!",
    "Rebalancing": "Periodically adjusting portfolio back to target allocations as prices drift. Example: If BTC grows from 30% to 45% of portfolio, sell some to restore 30% and buy underweighted assets.",
    "Regime Shift": "Major change in market behavior, often detected via sudden slope changes, correlation breaks, or volatility spikes. Example: crypto transitioning from bull market to bear market, or low-vol to high-vol periods.",
    "Risk Budget": "Total amount of risk you're willing to take, allocated across positions. Example: If max portfolio volatility is 60%, allocate that 'budget' by giving high-vol assets smaller weights. Like a financial allowance for risk.",
    "Risk Tolerance Profile": "User's comfort level with volatility and potential losses. Conservative = lower risk/lower return targets, Moderate = balanced, Aggressive = higher risk/higher return appetite. Affects position sizing and stop-loss levels.",
    "Slippage": "Difference between expected price and actual execution price. In volatile crypto markets, slippage can be 0.5-3%+. Always factor this into backtests or you'll overestimate real returns.",
    "Stop Loss": "Pre-set price level where you automatically exit a position to limit losses. If you buy at $100 with a 10% stop loss, you sell automatically if price hits $90. Essential risk management tool.",
    "Take Profit": "Pre-set price level where you automatically exit to lock in gains. The flip side of stop loss - captures profits before they evaporate. Example: Buy at $100, take profit at $125 (25% gain).",
    "Trailing Stop": "Stop loss that moves UP with price but never down. If you buy at $100 with 20% trailing stop, and price hits $200, your stop is now $160 (20% below $200). Locks in gains while allowing upside.",
    "Uncertainty Spread (Q0.95 - Q0.05)": "The width of the forecast distribution, measuring forecast confidence. Larger spread = more uncertainty. Example: If TRX has Q0.95=+80% and Q0.05=-40%, the spread is 120%, indicating HIGH uncertainty.",
    "Volatility": "Degree of price fluctuation over time, typically measured as standard deviation of returns. Annual volatility of 80% means the asset typically moves up or down 80% per year. Higher volatility = higher risk AND potential reward.",

    # === MARKET CONDITIONS & BEHAVIOR ===
    "Bear Market": "Prolonged downward price trend with pessimism and contraction. Features higher volatility, correlation convergence (everything falls together), and capital preservation focus. The 40% daily loss limit protects against catastrophic bear market losses.",
    "Bull Market": "Sustained upward price trend characterized by optimism and expansion. Typically features lower volatility, positive correlations, and rising returns. Risk: overconfidence leading to oversized positions. The system's volatility circuit breaker protects against sudden regime shifts.",
    "Crypto Winter": "Extended bear market specific to cryptocurrencies, often lasting 1-2 years. Characterized by 80%+ drawdowns, dead projects, and low trading volume. Survival requires strict position sizing, daily loss limits, and capital preservation - all enforced by this system's risk rules.",
    "FOMO (Fear of Missing Out)": "Emotional impulse to chase rising prices, often leading to buying peaks. Classic mistake: seeing DOGE up 500% and maxing out your position at the top. The system's 15% speculative asset cap prevents FOMO-driven overexposure to pump-and-dump tokens.",
    "Panic Selling": "Emotional liquidation during crashes, often at the worst prices. Opposite of FOMO but equally destructive. The flash crash protocol (buy when ≥3 assets drop ≥15%) turns panic into opportunity by deploying cash reserves during coordinated selloffs.",
    "Recency Bias": "Overweighting recent events in decision-making. Example: After a bull run, assuming high returns will continue forever. The system blends 70% historical returns with 30% recent trends to balance recency bias with long-term fundamentals.",
    "Survivorship Bias": "Analyzing only surviving assets, ignoring failed ones, leading to overestimated returns. Example: Backtesting only on coins that still exist today ignores the hundreds that went to zero. This is why the system enforces strict position sizing even on 'winners'.",

    # === FOREX TERMS ===
    "Avg. Daily Volume": "The average number of shares or contracts traded per day over a specified period, often the last month.",
    "Lot Size": "The standard volume of a forex trade, with a standard lot being 100,000 units of the base currency.",
    "Pip": "The smallest price increment in foreign exchange (forex) trading, typically 0.0001 for major currency pairs like EUR/USD.",
    "Swap": "The interest rate differential earned or paid for holding a forex position overnight.",

    # === FUNDAMENTAL ANALYSIS & VALUATION ===
    "Cheapness Rank (TEV/EBIT Screener)": "A ranking based on the Total Enterprise Value to Earnings Before Interest and Taxes (TEV/EBIT) multiple, where a lower rank indicates a cheaper stock.",
    "Current Ratio": "A liquidity ratio calculated as Current Assets divided by Current Liabilities.",
    "Debt/Equity": "A leverage ratio calculated as Total Debt divided by the Book Value of Equity.",
    "EPS PTM / EPS TTM": "Earnings Per Share for the previous or trailing twelve months, excluding extraordinary items.",
    "EV (or TEV)": "Enterprise Value, calculated as Market Capitalization plus Total Debt (including preferred equity) minus Cash and Equivalents.",
    "EV/EBITDA": "Enterprise Value divided by Earnings Before Interest, Taxes, Depreciation, and Amortization.",
    "FS_score": "A modified version of the Piotroski F-score, used to assess a company's financial health and stability, with higher scores indicating better quality.",
    "MF Quality Rank": "A ranking based on a company's return on capital, as defined by Joel Greenblatt, with higher ranks indicating better quality.",
    "MF Rank": "The average of the Magic Formula Quality Rank and Valuation Rank, used to rank stocks.",
    "MF Valuation Rank": "A ranking based on a company's Earnings Yield, defined as Operating Income after Depreciation divided by Enterprise Value.",
    "Mom. Quality Rank": "A proprietary measure of momentum consistency and monotonicity, with higher ranks indicating stronger momentum.",
    "Mom. Quarter / Mom. Year": "Measures of a stock's momentum over the past quarter or year, excluding the most recent month to avoid reversal effects.",
    "NCAV (% of MV)": "Net Current Asset Value as a percentage of Market Capitalization, calculated as (Current Assets – Total Liabilities – Preferred Equity) / Market Cap.",
    "Net Cash (% of MV)": "Net Cash as a percentage of Market Capitalization, calculated as (Cash & Equivalents – Total Liabilities – Preferred Equity) / Market Cap.",
    "P/B": "Price-to-Book ratio, calculated as Market Capitalization divided by Total Equity.",
    "P/E TTM": "Price-to-Earnings ratio based on trailing twelve months' earnings.",
    "P/FCF": "Price-to-Free Cash Flow ratio, calculated as Market Capitalization divided by (TTM Operating Cash Flow – Capital Expenditures).",
    "P/TanB": "Price-to-Tangible Book Value ratio, where tangible book value excludes intangible assets.",
    "Quarter Mom Rank": "A ranking based on idiosyncratic quarterly momentum, normalized relative to a stock's beta.",
    "ROC 5Y Avg.": "The five-year average of Return on Capital, calculated as EBIT divided by (Equity + Total Debt – Cash & Equivalents).",
    "Sh. Yield": "Shareholder Yield, representing the total return to shareholders via dividends, share buybacks, and debt reduction.",
    "TEV/EBIT Rank": "A cheapness rank based on the TEV/EBIT multiple, where a lower rank indicates a cheaper stock.",
    "TTM": "Trailing Twelve Months, a period used to calculate financial metrics based on the most recent 12 months of data.",
    "QV Quality Rank": "A comprehensive quality ranking based on fundamental and technical factors, with higher ranks indicating better quality.",

    # === REGULATORY BODIES ===
    "MiFID II": "The European Union's Markets in Financial Instruments Directive, aimed at increasing transparency and investor protection in financial markets.",
    "SEBI": "The Securities and Exchange Board of India, the country's primary securities regulator.",

    # === SYSTEM & UI TERMS ===
    "Data Wrangler": "Component that cleans and validates uploaded CSVs. Handles missing dates, zero prices, format inconsistencies. Can't fix extreme issues (50%+ missing data, multiple currencies in one file).",
    "Profile Lock": "Safety feature that prevents running Monte Carlo/Backtest/Stress Test with mismatched risk profiles. Ensures analysis matches your current risk tolerance. If locked, re-run CBQRA first.",
    "Stale Data Warning": "Alert when viewing results that don't match current settings. Example: looking at Monte Carlo from 'Aggressive' profile after switching to 'Conservative'. Always re-run analysis after changing profiles!",
}

# Active Risk Management Rule Descriptions (for UI display)
RISK_MANAGEMENT_RULES = {
    "correlation_rebalancing": {
        "name": "Correlation-Based Rebalancing",
        "threshold": "Correlation > 0.90",
        "action": "Reduce combined exposure by 20%",
        "severity": "WARNING",
        "rationale": "High correlation eliminates diversification benefits - your 'different' assets become the same trade. When XRP and XLM move together with 0.95 correlation, owning both doesn't reduce risk, it doubles it."
    },

    "volatility_circuit_breaker": {
        "name": "Volatility Circuit Breaker",
        "threshold": "30-day volatility > 2.5× baseline",
        "action": "Cut positions by 50% or tighten stops",
        "severity": "WARNING",
        "rationale": "Extreme volatility signals regime change or market instability. When volatility spikes, your stop-losses get hit more easily and tail risk explodes. Reduce exposure until markets stabilize."
    },

    "speculative_asset_cap": {
        "name": "Speculative Asset Limits",
        "threshold": "Memecoin/speculative allocation > 15%",
        "action": "Reduce to ≤15% + implement 25% trailing stop",
        "severity": "CRITICAL",
        "rationale": "Memecoins (DOGE, SHIB, PEPE), post-TGE dive-bombers, 'hopium' tokens, and rug-pull-prone assets have extreme downside risk with minimal fundamental support. These assets can drop 90%+ in days. The 15% cap + trailing stop limits catastrophic loss exposure."
    },

    "daily_loss_limit": {
        "name": "Daily Loss Circuit Breaker",
        "threshold": "Portfolio loss > 40% in one day",
        "action": "EMERGENCY: Exit all positions to cash",
        "severity": "CRITICAL",
        "rationale": "40% single-day loss indicates market catastrophe, black swan event, or exchange failure. Capital preservation becomes paramount. Recovering from 40% loss requires 67% gain - better to protect remaining capital and reassess. This is the nuclear option."
    },

    "flash_crash_protocol": {
        "name": "Flash Crash Opportunity",
        "threshold": "≥3 assets drop ≥15% within 1 hour",
        "action": "Deploy 30% cash reserves (buy the dip)",
        "severity": "INFO",
        "rationale": "Coordinated rapid crashes often result from cascading liquidations, exchange outages, or algorithm failures - not fundamental breakdown. These create exceptional buying opportunities as prices typically recover 50-80% within 24-48 hours. The flash crash detector turns systemic panic into profit."
    },

    "rebalance_drift": {
        "name": "Weekly Rebalancing Alert",
        "threshold": "Position drift ≥5% from target",
        "action": "Rebalance to restore target allocations",
        "severity": "INFO",
        "rationale": "As winners grow and losers shrink, your portfolio becomes concentrated in whatever happened to rise - changing your risk profile. If your 20% DOGE position grows to 40% through price appreciation, you're now taking 2× the intended risk. Weekly rebalancing prevents winner's curse and maintains disciplined allocation."
    }
}
